"""Provisional LSST instrument and observational settings.
See Optics and Observation Conditions spreadsheet at
https://docs.google.com/spreadsheets/d/1pMUB_OOZWwXON2dd5oP8PekhCT5MBBZJO1HV7IMZg4Y/edit?usp=sharing for list of
sources. """

camera = {'read_noise': 10,  # will be <10
               'pixel_scale': 0.2,
               'ccd_gain': 2.3}
"""
read_noise: std of noise generated by read-out (in units of electrons)
pixel_scale: scale (in arcseconds) of pixels
ccd_gain: electrons/ADU (analog-to-digital unit).
"""

g_band_obs = {'exposure_time': 15.,
                   'sky_brightness': 22.26,
                   'magnitude_zero_point': 28.30,
                   'num_exposures': 200, # baseline num of visits over 10 years (x2 since there are 2x15s exposures per visit)
                   'seeing': 0.77,
                   'psf_type': 'GAUSSIAN'}

r_band_obs = {'exposure_time': 15.,
                   'sky_brightness': 21.2,
                   'magnitude_zero_point': 28.13,
                   'num_exposures': 460,
                   'seeing': 0.73,
                   'psf_type': 'GAUSSIAN'}

i_band_obs = {'exposure_time': 15.,
                   'sky_brightness': 20.48,
                   'magnitude_zero_point': 27.79,
                   'num_exposures': 460,
                   'seeing': 0.71,
                   'psf_type': 'GAUSSIAN'}

"""
exposure_time: exposure time per image (in seconds)
sky_brightness: sky brightness (in magnitude per square arcseconds in units of electrons)
magnitude_zero_point: magnitude in which 1 count (e-) per second per arcsecond square is registered
num_exposures: number of exposures that are combined
seeing: Full-Width-at-Half-Maximum (FWHM) of PSF
psf_type: string, type of PSF ('GAUSSIAN' and 'PIXEL' supported)
"""

